# encedo-wkd upstream
# Install path: /opt/zextras/conf/nginx/extensions/upstream-wkd.conf
# Owner: zextras:zextras
# Included in http{} context

upstream wkd_server {
    server 127.0.0.1:8089;
    keepalive 4;
}
